### ISSUE TITLE
Expose Ping

### ISSUE THREAD

**Issue by SoftExpert** [craigpastro/pgmq-go#49]
Hello,

Is it possible to expose the **Ping** method from the **_pgx_** package ?

It might be useful when initializing a complex application logic ... 

Thank you in advance !

Best regards,
SoftExpert

**Comment by craigpastro** [comment]
Hi @SoftExpert! Yes, I think this is a great idea. Thank you. I can implement it when I have a few free cycles. Also happy to accept a PR!
